# Generated by Django 2.1.7 on 2019-03-25 15:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_waterpipeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='wifiCable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.IntegerField()),
                ('mbps', models.IntegerField()),
                ('from_field', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
